### ISSUE TITLE
Antialias isn't working in WHS.PostProcessor

### ISSUE THREAD

**Issue by sasha240100** [WhitestormJS/whitestorm.js#125]
Antialias parameter isn't working when using PostProcessor.
I debugged PostProcessor's params - all seems to be fine, but it doesn't work on example (post-processing/basic-glitch)

@typedef42 Why does it happen?

![image](https://cloud.githubusercontent.com/assets/7657429/19870611/feb59a88-9fb9-11e6-8d9d-7c9cde464d6a.png)

###### Version:
 - [x] r12 (dev) 
 - [ ] r11
 - [ ] r10
 - [ ] r9
 - [ ] r9 (dev)
 - [ ] r8
 - [ ] r7

###### Issue type:
 - [ ] Bug
 - [ ] Proposal/Enhancement
 - [ ] Question

------

<details> 
<summary> <b>Tested on: </b> </summary>
###### --- Desktop
   - [x] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### --- Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### --- IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by typedef42** [comment]
I could be wrong, but think it is normal because when we use the PostProcessor plugin, we don't use the basic THREE internal way of doing shaders. 

That means that this type of hardcoded comportement in THREE.js are not available anymore when using post processor, and thus EffectComposer underneath.

The way to have anti aliasing with an EffectComposer would be by adding a antialiasing pass, something like :

```js
let world = new WHS.World();
world.renderingPlugin = new WHS.PostProcessor();
let plugin = world.renderingPlugin;

plugin.createRenderPass(false);
plugin.createPass(composer => {
 const pass = new ShaderPass('antialias', 'FXAAShader');
pass.renderToScreen = true;
composer.addPass(pass);
});
```

I will port an antialias example from THREE.js FXAA or MSAA to test that.
