### ISSUE TITLE
Issue with div's named "scene"

### ISSUE THREAD

**Issue by cawoodm** [WhitestormJS/whitestorm.js#372]
https://codepen.io/anon/pen/OvvmKG

Works fine until you change the div id to "scene".

````html
<div id="scene"></div>
````

Black screen.

**Comment by hirako2000** [comment]
@cawoodm, I forked it [here](https://codepen.io/anon/pen/XEEgKa) with "scene"

Observe that the `App` object is initialised with an `ElementModule` that optionally take a dom element object.
```javascript
new WHS.ElementModule(document.getElementById('scene'))
```
Note: By default, `ElementModule` uses `document.body`, so even without a `div`, the app would render on the canvas, creating a div in the `body` part, with class named `whs-app`

As to why adding a div with id `scene` create a conflict, I don't know at first sight. 
@sasha240100

**Comment by sasha240100** [comment]
@hirako2000 Thanks for fast reply.
@cawoodm Issue closed?

**Comment by cawoodm** [comment]
I’m curious as to why it works with any id except „scene“.

**Comment by hirako2000** [comment]
That's because of your fined class here:
```css
#scene {
  width: 100vw;
  height: 100vh;
}
```

It does work, and render it, but is off screen in the codepen. Check your inspector, you will see it's below your `scene` div.

As explained, when the dom element object is not passed to the `ElementModule` constructor, `whs` will create a div in the document's `body`.

So
- By defining your div as `scene` without telling the element module about it, it fills the full device screen width and height (vw and vh in your css) with nothing thus show a black screen, then add the canvas below (non visible)
- By defining your div as `scene` telling the element module about it, it fills the full device screen width and height with the canvas inside that div (thus visible).

**Comment by hirako2000** [comment]
Note: I recommend against defining those vwidth and vheight to set the div/canvas size.
Rather leave it to the Resize module to deal with the window size. *unless* you want the canvas to be contained within part of the window, such as having control elements outside the canvas, or have multiple canvas.

**Comment by cawoodm** [comment]
OK... I had taken a three.js demo and added whs.js.
Sorry for the trouble!
