### ISSUE TITLE
[Bug] Broken example link on website; broken examples

### ISSUE THREAD

**Issue by dirkk0** [WhitestormJS/whitestorm.js#50]
Hi,

  I have some problems on http://whitestormjs.xyz/.

The link to the bottom right example is broken:
http://192.241.128.187/current/examples/basic_object.html
and the link top right gives me this error message on the console:
"Uncaught TypeError: api.construct is not a function"

Best,
  Dirk

**Comment by jackdalton** [comment]
Yep, we're currently in the midst of some big changes. Unfortunately, this involves some broken examples.

Thanks for pointing out the broken link, I wasn't aware of that! I'll fix it shortly.

**Comment by sasha240100** [comment]
Hi, @dirkk0 

That example is no linger supported since version 0.0.6 
I know that [Plugin/Color](http://192.241.128.187/current/examples/plugin_example.html) example doesn't work and i will fix it with next commit relating to #48.
I will update links on site as soon as i can:)

Check also [those](http://192.241.128.187/current/examples/plugin_example.html) examples.

**Comment by sasha240100** [comment]
@dirkk0 @jackdalton Issue moved to https://github.com/WhitestormJS/whitestormjs.github.io/issues/3

**Comment by jackdalton** [comment]
Fixed by [51e48d8](https://github.com/WhitestormJS/whitestormjs.github.io/commit/51e48d8c4e2dc76a86f60f5a0695836ac8e5f7e5).
